### PR TITLE
CORES specific language

### PR DESCRIPTION
**Pull request by decaluwe**
1. Adding sections specifically developed during our group meeting on 26 April, 2019.

- Purpose
- Scope
- Standards and relation to CSM policies
- Reporting options
- Consequences and Enforcement

4. Created table of contents
6. Added content on annual review and approval

### CODE REVIEW

**Comment by decaluwe** [comment]
Okay, let's close out the `CODE_OF_CONDUCT.md` pull request.

Can people go take a look at the most recent suggested version and provide any feedback?  You can click on the individual commits, above, or click here to see what it looks like:

https://github.com/coresresearch/coresresearch/blob/6beb3bb8c28dc68fc5e969df855493459d8eaeb1/CODE_OF_CONDUCT.md

If you have feedback, leave a comment here, or if you are good with it as is, you can just give a thumbs up 👍 (click on the smiley face in the bar above this comment and pick your reaction).  For documents like this, I'm going to want unanimous approval, before it gets posted - if anyone has an issue or thinks it can/should be improved, we will address those concerns before approving.

Thanks!
Steven

**Comment by amylebar** [comment]
The content looks good to me.  Only a few minor typos I found:

1. Under Purpose, second paragraph begins with "Discriminationon."  Should be "Discrimination"
2. Under Reporting Guidelines and Options, section a.i. uses "directly" redundantly

**Comment by decaluwe** [comment]
I've seen it spelled both ways 😉 

Thanks for catching those, @amylebar - it prompted me to give a closer read and caught a number of other typos.

Fixing and will push fixes, soon.

**Comment by decaluwe** [comment]
@pweddle - any input?  Once you approve, we can merge this.

**Comment by pweddle** [comment]
1. Under Scope first paragraph, last sentence should be "and to the group PI".
2. Under "Other reporting options", do you want to include CARE @ Mines (https://www.mines.edu/student-life/care/) or SPEAKUP @ Mines (https://www.mines.edu/title-ix/)

**Comment by decaluwe** [comment]
Thanks for the input, @pweddle 

1. Thanks - fixed that and caught another typo.
2. Not sure what you mean here.  I currently include CARE, SPEAKUP, and a direct link to Title IX reporting.  Are you saying one or the other of these is more/less preferable?

**Comment by pweddle** [comment]
Nope, just didn't see it explicitly.  I'm good with the document as written.

**Pull request merged**
